package co.edu.icesi.classmicroservice.model;

public enum TipoClase {
    AEROBIC, SPINNING, ZUMBA, YOGA, PILATES, GAP, CROSSFIT, FUNCIONAL, CARDIO, MUSCULACION, NATACION, CICLISMO, ESCALADA, BALONCESTO, FUTBOL, VOLEIBOL, TENIS, GIMNASIA, BOXEO, KICKBOXING, KARATE, JUDO, TAEKWONDO, JIUJITSU, MMA, LUCHA, DANZA, BALLET, SALSA, BACHATA, MERENGUE, REGGAETON, HIPHOP, BREAKDANCE, TANGO, FLAMENCO, FOLKLORE, CUMBIA, ROCK, POP, ELECTRONICA, REGGAE, RAP, TRAP, METAL, PUNK, INDIE, JAZZ, BLUES, CLASICA, OPERA, FOLK, COUNTRY,  URBANO, INFANTIL, ADULTO, JUVENIL, SENIOR, MIXTA, MUJERES, HOMBRES, MIXTO
}
